apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx      
    demo: service
spec:    
  containers:
  - name: nginx-pod
    image: nginx
    ports:
    containerPort: 8080

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
    demo: service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080    
