apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeport
  labels:
    app: nodeport
spec:
  containers:
  - name: nodeport
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
spec:
type: NodePort 
  selector:
    app: nodeport
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  
