apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
spec:
 containers:
  - name: hello-pod
    image: nginx
    ports:
    - conterPort: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

