apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    ports:
    - containerPort: 80
    env:
    #dont hardcode config map values
    - name: course:
      valueFrom:
        configMapkeyRef:
          name: devop-config
          key: course
    - name: trainer
      valueFrom:
        configMapkeyRef:
          name: devop-config
          key: trainer

